# Generated by Django 6.0.4 on 2026-05-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=20)),
                ('duracao', models.CharField(max_length=20)),
                ('poster', models.URLField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('diretor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
